# Generated by Django 3.1.5 on 2021-02-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210207_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='photo',
            field=models.ImageField(default='', upload_to='media/foods/'),
            preserve_default=False,
        ),
    ]
