# Generated by Django 3.1.5 on 2021-02-07 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210207_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(days=1), '1 day'), (datetime.timedelta(days=3), '3 days'), (datetime.timedelta(days=5), '5 days')], default=datetime.timedelta(days=1)),
        ),
    ]
