# Generated by Django 3.1.5 on 2021-02-07 12:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_coupon_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(default=accounts.models.random_string, max_length=100),
        ),
    ]
