# Generated by Django 3.1.5 on 2021-02-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210207_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='size',
            field=models.PositiveIntegerField(blank=True, choices=[(6, 6), (8, 8), (12, 12)], default=6),
            preserve_default=False,
        ),
    ]
