# Generated by Django 3.1.5 on 2021-02-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_food_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='size',
            field=models.PositiveIntegerField(choices=[(6, 6), (8, 8), (12, 12)], null=True),
        ),
    ]
