# Generated by Django 3.1.5 on 2021-02-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210207_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='size',
            field=models.PositiveIntegerField(choices=[(6, 6), (8, 8), (12, 12)], default=0, null=True),
        ),
    ]
